title: APT::WTF - APTortellini's blog
author:
  name: Advanced Persistent Tortellini
  #email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Home of the Advanced Persistent Tortellini - aka APTortellini, an Italian collective of hackers
  publishing technical research regarding offensive security.

show_excerpts: false # set to true to show excerpts on the homepage
markdown: kramdown
highlighter: rouge
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: auto

  # generate social links in footer
  social_links:
    twitter: APTortellini
    github:  APTortellini
    telegram: aptortellini

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-spaceship
 - rouge
